language: python2

sudo: true

install:
- sudo python -m pip install -r requirements.txt

script:
    - ~/.dronekit/sitl/copter-3.3/apm --home=-35.363261,149.165230,584,353 --model=quad &
    - python sitl/sitl.py 5760 sitl/test_mission.json

