sudo: required
services: 
   - docker

script:
   - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
   - docker build . -t otoojaursk/aerial-lidar:latest
   - docker push otoojaursk/aerial-lidar:latest

