language: python2

sudo: true

install:
- sudo apt-get install python-dev python-opencv python-wxgtk3.0 python-pip python-matplotlib python-pygame python-lxml
  sudo pip install MAVProxy
- echo "export PATH=$PATH:$HOME/.local/bin" >> ~/.bashrc

script:
    - make runsitl
