language: python2

sudo: true

install:
- sudo apt-get install python-dev python-opencv python-wxgtk3.0 python-pip python-matplotlib python-pygame python-lxml
- sudo python -m pip -r requirements.txt

script:
    - ~/.dronekit/sitl/copter-3.3/apm  & 
    - python sitl/sitl.py 5760 sitl/test_mission.json

